########################
##### EXPERIMENTAL #####
########################

#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME PRE-BUILT                                                                         #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  device_name: nspanel
  wifi_ssid: nspanel
  wifi_password: NSPanel_Blueprint


packages:
  # yamllint disable rule:colons
  # Core packages
  core_package:       !include ../esphome/nspanel_esphome_core.yaml  # Core configuration for basic functionality
  # standard_package:   !include ../esphome/nspanel_esphome_standard.yaml  # Standard (includes packages listed)
  ota_http:           !include ../esphome/nspanel_esphome_addon_ota_http.yaml  # Required for pre-built firmware
  # Optional (and recommended) packages
  hw_buzzer:          !include ../esphome/nspanel_esphome_standard_hw_buzzer.yaml
  hw_relays:          !include ../esphome/nspanel_esphome_standard_hw_relays.yaml
  hw_temperature:     !include ../esphome/nspanel_esphome_standard_hw_temperature.yaml
  # page_alarm:         !include ../esphome/nspanel_esphome_standard_page_alarm.yaml
  # page_blank:         !include ../esphome/nspanel_esphome_standard_page_blank.yaml
  page_buttons:       !include ../esphome/nspanel_esphome_standard_page_buttons.yaml
  page_climate:       !include ../esphome/nspanel_esphome_standard_page_climate.yaml
  page_confirm:       !include ../esphome/nspanel_esphome_standard_page_confirm.yaml
  page_cover:         !include ../esphome/nspanel_esphome_standard_page_cover.yaml
  page_entities:      !include ../esphome/nspanel_esphome_standard_page_entities.yaml
  page_fan:           !include ../esphome/nspanel_esphome_standard_page_fan.yaml
  # page_keyb_num:      !include ../esphome/nspanel_esphome_standard_page_keyb_num.yaml
  page_light:         !include ../esphome/nspanel_esphome_standard_page_light.yaml
  # page_media_player:  !include ../esphome/nspanel_esphome_standard_page_media_player.yaml
  page_notification:  !include ../esphome/nspanel_esphome_standard_page_notification.yaml
  page_qrcode:        !include ../esphome/nspanel_esphome_standard_page_qrcode.yaml
  page_settings:      !include ../esphome/nspanel_esphome_standard_page_settings.yaml
  # page_utilities:     !include ../esphome/nspanel_esphome_standard_page_utilities.yaml
  #page_weather:       !include ../esphome/nspanel_esphome_standard_page_weather.yaml
  upload_tft:         !include ../esphome/nspanel_esphome_standard_upload_tft.yaml
  # Optional advanced and add-on configurations
  # addon_advanced:     !include ../esphome/nspanel_esphome_advanced.yaml
  # addon_ble_tracker:  !include ../esphome/nspanel_esphome_addon_ble_tracker.yaml
  # addon_ble_proxy:    !include ../esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
  # addon_climate_cool: !include ../esphome/nspanel_esphome_addon_climate_cool.yaml
  # addon_climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml
  # addon_climate_dual: !include ../esphome/nspanel_esphome_addon_climate_dual.yaml
  # addon_cover:        !include ../esphome/nspanel_esphome_addon_cover.yaml
  # yamllint enable rule:colons

captive_portal:
  id: ap_captive_portal

dashboard_import:
  package_import_url: github://Blackymas/NSPanel_HA_Blueprint/prebuilt/nspanel_esphome_prebuilt.yaml@main
  import_full_config: false

esp32_ble:
  id: ble

esp32_improv:
  id: ble_improv
  authorizer: none

esp32_ble_server:
  id: ble_server

esphome:
  name_add_mac_suffix: true
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_PREBUILT

improv_serial:
  id: serial_improv

logger:
  baud_rate: 115200

ota:
  - id: !extend ota_std
    password: !remove

script:
  - id: !extend dump_config_packages  # Defined by nspanel_esphome_core_base.yaml
    then:
      - lambda: |-
          ESP_LOGCONFIG("${project_tag}", "  - Pre-built");

wifi:
  networks: !remove
  ap: {}
  power_save_mode: LIGHT  # To make it compatible with BLE
...
