---
packages:
  core_package: !include esphome/nspanel_esphome_core.yaml  # The core part of NSPanel (display, PSRAM, etc.)
  standard_package: !include esphome/nspanel_esphome_standard.yaml  # The basic functionalities described on our documentation
  upload_tft_package: !include esphome/nspanel_esphome_addon_upload_tft.yaml  # Everything you need to upload TFT to Nextion
  display_light: !include esphome/nspanel_esphome_addon_display_light.yaml  # Show the display as a light in Home Assistant
...
