---
substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/dummy"

packages:
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml

esp32:
  framework:
    type: arduino
...
