---
packages:
  ard_common: !include esphome_ard_common.yaml
  basic_package: !include ../nspanel_esphome.yaml  # Basic package
  display_as_light: !include ../esphome/nspanel_esphome_addon_display_light.yaml
...
