---
substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/dummy"

packages:
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_ble_tracker: !include ../esphome/nspanel_esphome_addon_ble_tracker.yaml

esp32:
  framework:
    type: esp-idf
    version: 5.0.2
    platform_version: 6.3.2
...
