---
substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/dummy"

packages:
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_climate_cool: !include ../esphome/nspanel_esphome_addon_climate_cool.yaml
  addon_bluetooth_proxy: !include ../esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
...
