#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - QRCODE                                                                     #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_QRCODE: '22'
  PAGE_ID_QRCODE: '17'

api:
  actions:
    # Dynamically displays QR codes on the ESPHome UI for sharing information such as WiFi passwords or website links.
    - action: qrcode
      variables:
        title: string   # Heading or title for the QR code, offering context or instructions.
        qrcode: string  # Data or URL to be encoded into the QR code.
        show: bool      # Flag to immediately display the QR code page upon action invocation.
      then:
        - lambda: |-
            if (show)
              goto_page_id->execute(${PAGE_ID_QRCODE}, true);
            display_component_update_text->execute(get_component(${PAGE_ID_QRCODE}, "qrcode_label"), title.c_str());
            display_component_update_text->execute(get_component(${PAGE_ID_QRCODE}, "qrcode_body"), qrcode.c_str());

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_STANDARD_QRCODE

script:
  - id: !extend boot_package_register
    then:
      - lambda: boot_package_register_add->execute(${BOOT_STEP_PAGE_QRCODE}, "PAGE_QRCODE", "Page QRcode");
...
