#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Confirm                                                               #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  please_confirm: "Please confirm"
  BOOT_STEP_PAGE_CONFIRM: '13'
  PAGE_ID_CONFIRM: '26'

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_STANDARD_PAGE_CONFIRM

globals:
  #### Localization (MUI) ####
  - id: mui_please_confirm
    type: std::string
    restore_value: true
    initial_value: '"${please_confirm}"'

script:
  - id: !extend boot_initialize
    then:
      - lambda: |-
          display_component_initialize->execute(${PAGE_ID_CONFIRM}, "title", true);
          display_component_initialize->execute(${PAGE_ID_CONFIRM}, "body", true);

  - id: !extend boot_package_register
    then:
      - lambda: boot_package_register_add->execute(${BOOT_STEP_PAGE_CONFIRM}, "PAGE_CONFIRM", "Page Confirm");

  - id: !extend button_click_short
    then:
      - lambda: |-
          if (is_button_in_mask(button_id, PageButtonsMaskConfirm)) {
            goto_page_id->execute(${PAGE_ID_CONFIRM}, true);
            set_component_value->execute(${PAGE_ID_CONFIRM}, "page_id", page_id);
            set_component_text->execute(${PAGE_ID_CONFIRM}, "page_name", page_names[page_id]);
            set_component_text->execute(${PAGE_ID_CONFIRM}, "component", get_button_name(button_id));
            static DisplayComponent* confirm_body = get_component(${PAGE_ID_CONFIRM}, "body");
            display_component_update_text->execute(confirm_body, buttonpage_buttons[button_id-1].label->text);
          }

  - id: !extend page_changed
    then:
      - lambda: |-
          if (current_page_id == ${PAGE_ID_CONFIRM})
            page_confirm->execute();

  - id: page_confirm
    mode: restart
    then:
      - script.execute:
          id: display_wrapped_text
          page_id: ${PAGE_ID_CONFIRM}
          component: title
          text_to_display: !lambda return id(mui_please_confirm).c_str();
          line_length_limit: 15

  - id: !extend set_var_string
    then:
      - lambda: |-
          if (component == "mui_please_confirm")
            id(mui_please_confirm) = val;

  - id: !extend stop_all
    then:
      - script.stop: page_confirm
...
