#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Blank                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_BLANK: '1UL << 27'

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_PAGE_BLANK}, "Page Blank");

  - id: !extend boot_sequence
    then:
      - lambda: |-
          boot_progress->execute(${BOOT_STEP_PAGE_BLANK}, "Page Blank");

  - id: page_blank
    mode: restart
    then:
      - lambda: |-
          send_command->execute("tm_esphome.en=0");
          set_component_text->execute("blank", "esp_version", "FW: ${version}");  // ESPHome version
          #ifdef ARDUINO
          set_component_text->execute("blank", "framework", "Arduino");
          #else
          set_component_text->execute("blank", "framework", "ESP-IDF");
          #endif

  - id: !extend page_changed
    then:
      - if:
          condition:
            - text_sensor.state:
                id: current_page
                state: blank
          then:
            - script.execute: page_blank

  - id: !extend stop_all
    then:
      - script.stop: page_blank
...
