#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Weather                                                               #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if  (
                  page_id == 1  // Page Home
                  and id(weather_pic) > 1  // Some weather pic is shown
                  and api_server->is_connected()
                  and
                    (
                      component_id == 5     // outdoor temperature
                      or component_id == 7  // weather
                    )
                ) {
              goto_page->execute("weather01");
            }

globals:
  - id: weather_pic
    type: uint8_t
    restore_value: false
    initial_value: '1'

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          ESP_LOGCONFIG("script.boot_progress_dump", " - Page Weather:         %s", is_boot_step_completed(BOOT_STEP_PAGE_WEATHER) ? "Completed" : "PENDING");

  - id: !extend page_changed
    then:
      - lambda: |-
          if (current_page->state == "weather01") page_weather01->execute();
          else if (current_page->state == "weather02") page_weather02->execute();
          else if (current_page->state == "weather03") page_weather03->execute();
          else if (current_page->state == "weather04") page_weather04->execute();
          else if (current_page->state == "weather05") page_weather05->execute();

  - id: !extend page_home
    then:
      - lambda: |-
          disp1->set_component_pic("weather", id(weather_pic));

  - id: page_weather
    mode: restart
    parameters:
      page_number: uint
    then:  # There's nothing here so far
  - id: page_weather01
    mode: restart
    then:
      - script.execute:
          id: page_weather
          page_number: 1
  - id: page_weather02
    mode: restart
    then:
      - script.execute:
          id: page_weather
          page_number: 2
  - id: page_weather03
    mode: restart
    then:
      - script.execute:
          id: page_weather
          page_number: 3
  - id: page_weather04
    mode: restart
    then:
      - script.execute:
          id: page_weather
          page_number: 4
  - id: page_weather05
    mode: restart
    then:
      - script.execute:
          id: page_weather
          page_number: 5

  - id: !extend set_var_int
    then:
      - lambda: |-
          if (component == "weather_pic" and val>=1 and val<=15) {
            if (id(weather_pic) != val) {
              id(weather_pic) = static_cast<uint8_t>(val);
              delay(10*disp1->queue_size()+tf_uart->available());
              if (current_page->state == "home") disp1->set_component_pic("weather", val);
            }
            boot_progress->execute(BOOT_STEP_PAGE_WEATHER, "Page Weather");
          }

  - id: !extend stop_all
    then:
      - script.stop: page_weather
      - script.stop: page_weather01
      - script.stop: page_weather02
      - script.stop: page_weather03
      - script.stop: page_weather04
      - script.stop: page_weather05
...
