#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Climate control - Dual                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################
---
substitutions:
  ##### DO NOT CHANGE THIS #####
  addon_climate_dual: "true"
  NSPANEL_HA_BLUEPRINT_ADDON_CLIMATE_DUAL: "true"
  ##############################

climate:
  - id: !extend thermostat_embedded
    min_cooling_off_time: ${min_off_time}s
    min_heating_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    min_heating_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
    preset:
      - name: "Off"
        default_target_temperature_high: ${target_high} ${temp_units}
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_high: ${target_high} ${temp_units}
        default_target_temperature_low: ${target_low} ${temp_units}
        mode: "heat_cool"

packages:
  climate_base_package: !include nspanel_esphome_addon_climate_base.yaml
...
