#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - HARDWARE - RELAYS                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_HW_RELAYS: '7'
  GPIO_RELAY_1_PIN: '22'
  GPIO_RELAY_1_INVERTED: 'false'
  GPIO_RELAY_2_PIN: '19'
  GPIO_RELAY_2_INVERTED: 'false'
  TAG_STANDARD_HW_RELAYS: standard_hw_relays

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_STANDARD_HW_RELAYS

globals:
  - id: relay1_local
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: relay1_fallback
    type: bool
    restore_value: true
    initial_value: 'false'

  - id: relay2_local
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: relay2_fallback
    type: bool
    restore_value: true
    initial_value: 'false'

  ##### Relay icons #####
  - id: relay1_icon
    type: DisplayComponent*
    restore_value: false
  - id: home_relay1_icon
    type: char[5]
    restore_value: true
    initial_value: ''
  - id: home_relay1_icon_color
    type: uint16_t
    restore_value: true
    initial_value: '65535'

  - id: relay2_icon
    type: DisplayComponent*
    restore_value: false
  - id: home_relay2_icon
    type: char[5]
    restore_value: true
    initial_value: ''
  - id: home_relay2_icon_color
    type: uint16_t
    restore_value: true
    initial_value: '65535'

script:
  - id: !extend boot_package_register
    then:
      - lambda: boot_package_register_add->execute(${BOOT_STEP_HW_RELAYS}, "HW_RELAYS", "HW Relays");

  - id: !extend boot_sequence
    then:
      - lambda: |-
          ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Boot starting");
          ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Set chip relay 1");
          id(relay1_icon) = get_component(${PAGE_ID_HOME}, "chip_relay1");
          if (not id(relay1_icon)) {
            ESP_LOGW("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Error allocating component 'chip_relay1'");
          } else {
            display_component_update_text->execute(id(relay1_icon), id(home_relay1_icon));
            display_component_update_color->execute(id(relay1_icon), id(home_relay1_icon_color));
            display_component_update_visibility->execute(id(relay1_icon), relay_1->state);
          }

          ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Set chip relay 2");
          id(relay2_icon) = get_component(${PAGE_ID_HOME}, "chip_relay2");
          if (not id(relay1_icon)) {
            ESP_LOGW("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Error allocating component 'chip_relay2'");
          } else {
            display_component_update_text->execute(id(relay2_icon), id(home_relay2_icon));
            display_component_update_color->execute(id(relay2_icon), id(home_relay2_icon_color));
            display_component_update_visibility->execute(id(relay2_icon), relay_2->state);
          }

          ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Boot completed");

  - id: !extend display_component_action  # Defined by nspanel_esphome_core_hw_display.yaml
    then:
      - lambda: |-
          if (page_id == ${PAGE_ID_HOME}) {
            if (component == "chip_relay1") {
              ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Chip new val");
              id(home_relay1_icon_color) = color565(color);
              copyStringToCharArray(id(home_relay1_icon), txt);
              if (id(relay1_icon))
                display_component_update_visibility->execute(id(relay1_icon), relay_1->state);
              ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Chip set");
            }
            else if (component == "chip_relay2") {
              ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Chip new val");
              id(home_relay2_icon_color) = color565(color);
              copyStringToCharArray(id(home_relay2_icon), txt);
              if (id(relay2_icon))
                display_component_update_visibility->execute(id(relay2_icon), relay_2->state);
              ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - set");
            }
          }

  - id: !extend ha_button
    then:
      - lambda: |-
          if  (component == "hw_bt_left" and command == "short_click" and
              (id(relay1_local) or
                (id(relay1_fallback) and (!api_server->is_connected() or !wifi_component->is_connected()))))
            relay_1->toggle();
          else if  (component == "hw_bt_right" and command == "short_click" and
              (id(relay2_local) or
                (id(relay2_fallback) and (!api_server->is_connected() or !wifi_component->is_connected()))))
            relay_2->toggle();

  - id: !extend page_home
    then:
      - script.execute: refresh_relays

  - id: refresh_relays
    mode: restart
    then:
      - lambda: |-
          if (id(relay1_icon))
            display_component_update_visibility->execute(id(relay1_icon), relay_1->state);
          if (id(relay2_icon))
            display_component_update_visibility->execute(id(relay2_icon), relay_2->state);

  - id: !extend set_var_bool
    then:
      - lambda: |-
          if (component == "hw_relay_1_local") {
            id(relay1_local) = val;
            ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Relay 1 - Local: %s", YESNO(id(relay1_local)));
          } else if (component == "hw_relay_1_fallback") {
            id(relay1_fallback) = val;
            ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Relay 1 - Fallback: %s", YESNO(id(relay1_fallback)));
          } else if (component == "hw_relay_2_local") {
            id(relay2_local) = val;
            ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Relay 2 - Local: %s", YESNO(id(relay2_local)));
          } else if (component == "hw_relay_2_fallback") {
            id(relay2_fallback) = val;
            ESP_LOGV("${TAG_STANDARD_HW_RELAYS}", "HW Relay - Relay 2 - Fallback: %s", YESNO(id(relay2_fallback)));
          }

  - id: !extend stop_all
    then:
      - lambda: |-
          refresh_relays->stop();

switch:
  ##### PHYSICAL SWITCH 1 #####
  - name: Relay 1
    platform: gpio
    id: relay_1
    pin:
      number: ${GPIO_RELAY_1_PIN}
      inverted: ${GPIO_RELAY_1_INVERTED}
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - lambda: |-
            if (id(relay1_local)) {
              id(button_left_state) = true;
              refresh_relays->execute();
              hw_buttons_bars_refresh->execute(1);
            }
    on_turn_off:
      then:
        - lambda: |-
            if (id(relay1_local)) {
              id(button_left_state) = false;
              refresh_relays->execute();
              hw_buttons_bars_refresh->execute(1);
            }

  ##### PHYSICAL SWITCH 2 ######
  - name: Relay 2
    platform: gpio
    id: relay_2
    pin:
      number: ${GPIO_RELAY_2_PIN}
      inverted: ${GPIO_RELAY_2_INVERTED}
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - lambda: |-
            if (id(relay2_local)) {
              id(button_right_state) = true;
              refresh_relays->execute();
              hw_buttons_bars_refresh->execute(2);
            }
    on_turn_off:
      then:
        - lambda: |-
            if (id(relay2_local)) {
              id(button_right_state) = false;
              refresh_relays->execute();
              hw_buttons_bars_refresh->execute(2);
            }

time:
  - id: !extend time_provider
    on_time:
      - seconds: 0
        then:
          - lambda: |-
              refresh_relays->execute();
...
