#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - HARDWARE - BUZZER                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
# nspanel_esphome_core.yaml:
#   api.actions.notification_show
###############################

---
substitutions:
  BOOT_STEP_HW_BUZZER: '1UL << 4'
  tone_touch_press: "Touch:d=16,o=5,b=180:g"
  tone_touch_release: "Release:d=32,o=5,b=180:g,g"

api:
  id: !extend api_server
  actions:
    - action: rtttl_play
      variables:
        tone: string  # The RTTTL string for the melody to be played. It should follow the RTTTL format, including the melody's name, default settings, and a sequence of notes.
      then:
        - rtttl.stop
        - rtttl.play: !lambda return tone;

display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if (buzzer_touch_feedback->state)
              buzzer->play(touch_event ? "${tone_touch_press}" : "${tone_touch_release}");

output:
  # Buzzer output
  - id: buzzer_out
    platform: ledc
    pin:
      number: 21

##### ENABLE RINGTONE MUSIC SUPPORT #####
rtttl:
  id: buzzer
  output: buzzer_out

script:
  - id: !extend boot_progress_dump
    then:
      - lambda: |-
          boot_progress_dump_item->execute(${BOOT_STEP_HW_BUZZER}, "HW Buzzer");

  - id: !extend boot_sequence
    then:
      - lambda: |-
          boot_progress->execute(${BOOT_STEP_HW_BUZZER}, "HW Buzzer");

  - id: !extend page_boot
    then:
      - lambda: |-
          if (notification_sound->state) {
            boot_log->execute("Boot", "Play boot sound");
            buzzer->play("two short:d=4,o=5,b=100:16e6,16e6");
          }

switch:
  - id: buzzer_touch_feedback
    name: Touch screen feedback sound
    platform: template
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    internal: false
    icon: mdi:volume-high
...
