#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Cover                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_COVER: '14'
  PAGE_ID_COVER: '11'

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_STANDARD_PAGE_COVER

script:
  - id: !extend boot_package_register
    then:
      - lambda: boot_package_register_add->execute(${BOOT_STEP_PAGE_COVER}, "PAGE_COVER", "Page Cover");

  - id: !extend event_from_display
    then:
      - lambda: |-
          if (page == "cover") {
            const std::string key = json["key"];
            if (key == "position") {
              const std::string value = json["value"];
              ha_call_action->execute("cover.set_cover_position", key.c_str(),
                                      value.c_str(), detailed_entity->state.c_str());
            } else
              ha_call_action->execute(("cover." + key).c_str(), "", "", detailed_entity->state.c_str());
          }
...
