#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Bluetooth proxy                                                        #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################
---

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_ADDON_BLUETOOTH_PROXY

bluetooth_proxy:
  id: ble_proxy

packages:
  ble_base_package: !include nspanel_esphome_addon_ble_tracker.yaml

script:
  - id: !extend dump_config
    then:
      - lambda: |-
          // Check if this is installed with Arduino
          #ifdef USE_ARDUINO
            # yamllint disable rule:line-length
            #error "Invalid settings for add-on Bluetooth Proxy. Arduino framework is not supported when using Bluetooth in this project."
            # yamllint enable rule:line-length
          #endif
          ESP_LOGCONFIG("${project_tag}", "Add-on Bluetooth Proxy:");
          ESP_LOGCONFIG("${project_tag}", "  Mode:        %s", ble_proxy->has_active() ? "Active" : "Passive");
          ESP_LOGCONFIG("${project_tag}", "  Connections: %i", int(ble_proxy->get_bluetooth_connections_limit() -
                                                                    ble_proxy->get_bluetooth_connections_free()));
          ESP_LOGCONFIG("${project_tag}", "  Limit:       %i", int(ble_proxy->get_bluetooth_connections_limit()));

  - id: !extend dump_config_packages  # Defined by nspanel_esphome_core_base.yaml
    then:
      - lambda: |-
          ESP_LOGCONFIG("${project_tag}", "  - Add-on - Bluetooth Proxy");

# Set Wi-Fi power save mode to "LIGHT" as required for Bluetooth on ESP32
wifi:
  power_save_mode: LIGHT
...
