#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME STANDARD                                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_STANDARD

packages:
  # yamllint disable rule:colons
  ## Standard packages
#  hw_buzzer:          !include nspanel_esphome_standard_hw_buzzer.yaml
#  hw_relays:          !include nspanel_esphome_standard_hw_relays.yaml
#  hw_temperature:     !include nspanel_esphome_standard_hw_temperature.yaml
#  page_alarm:         !include nspanel_esphome_standard_page_alarm.yaml
#  page_blank:         !include nspanel_esphome_standard_page_blank.yaml
#  page_buttons:       !include nspanel_esphome_standard_page_buttons.yaml
#  page_climate:       !include nspanel_esphome_standard_page_climate.yaml
#  page_confirm:       !include nspanel_esphome_core_page_confirm.yaml
#  page_cover:         !include nspanel_esphome_standard_page_cover.yaml
#  page_entities:      !include nspanel_esphome_standard_page_entities.yaml
#  page_fan:           !include nspanel_esphome_standard_page_fan.yaml
#  page_keyb_num:      !include nspanel_esphome_standard_page_keyb_num.yaml
#  page_light:         !include nspanel_esphome_standard_page_light.yaml
#  page_media_player:  !include nspanel_esphome_standard_page_media_player.yaml
#  page_notification:  !include nspanel_esphome_standard_page_notification.yaml
#  page_qrcode:        !include nspanel_esphome_standard_page_qrcode.yaml
#  page_settings:      !include nspanel_esphome_standard_page_settings.yaml
#  page_utilities:     !include nspanel_esphome_standard_page_utilities.yaml
#  page_weather:       !include nspanel_esphome_standard_page_weather.yaml
  upload_tft:         !include nspanel_esphome_standard_upload_tft.yaml
  # yamllint enable rule:colons
...
