#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - HARDWARE - Memory                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
###############################

---
substitutions:
  BOOT_STEP_HW_MEMORY: '1UL << 6'

psram:
  id: ext_ram

script:
  - id: !extend boot_progress_dump
    then:
      - script.execute:
          id: boot_progress_dump_item
          step: ${BOOT_STEP_HW_MEMORY}
          step_name: HW Memory

  - id: !extend boot_sequence
    then:
      - script.execute:
          id: boot_progress
          step: ${BOOT_STEP_HW_MEMORY}
          step_name: HW Memory

  - id: !extend dump_config
    then:
      - lambda: |-
          #include <esp_heap_caps.h>
          // Report memory
          const size_t internal_heap_size = heap_caps_get_total_size(MALLOC_CAP_INTERNAL);
          const size_t internal_heap_size_free = heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
          ESP_LOGCONFIG("${project_tag}", "  Free heap:");

          if (internal_heap_size != 0) {
            ESP_LOGCONFIG("${project_tag}", "    Internal:  %7d bytes (%0.1f%%)", internal_heap_size_free,
                    ((float)internal_heap_size_free / internal_heap_size) * 100.0f);
          } else {
            ESP_LOGCONFIG("${project_tag}", "    Internal:  %7d bytes", internal_heap_size_free);
          }

          #ifdef USE_PSRAM
          const size_t psram_heap_size = heap_caps_get_total_size(MALLOC_CAP_SPIRAM);
          const size_t psram_heap_size_free = heap_caps_get_free_size(MALLOC_CAP_SPIRAM);
          if (psram_heap_size != 0) {
            ESP_LOGCONFIG("${project_tag}", "    PSRAM:     %7d bytes (%0.1f%%)", psram_heap_size_free,
                    ((float)psram_heap_size_free / psram_heap_size) * 100.0f);
          } else {
            ESP_LOGCONFIG("${project_tag}", "    PSRAM:     %7d bytes", psram_heap_size_free);
          }
          #endif
...
