---
name: ESPHome Memory Analysis

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**/*.yaml'
      - 'components/nspanel_ha_blueprint/**'
  pull_request:
    paths:
      - '**/*.yaml'
      - 'components/nspanel_ha_blueprint/**'

jobs:
  analyze:
    name: ESPHome Memory Analysis (dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ESPHome memory analysis (dev)
        run: |
          docker run --rm \
            -v $PWD:/config \
            esphome/esphome:dev \
            analyze-memory nspanel_esphome.yaml \
            | tee memory_report.txt

      - name: Upload memory analysis report
        uses: actions/upload-artifact@v4
        with:
          name: esp-memory-report
          path: memory_report.txt
...
